name: Go CI

on:
  push:
    branches: [ "**" ]
  pull_request:

defaults:
  run:
    working-directory: snirouter  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: snirouter/go.mod  
          cache: true
          cache-dependency-path: snirouter/go.sum

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -trimpath -ldflags="-s -w" -o sni-panel .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sni-panel-linux-amd64
          path: snirouter/sni-panel     
